### ISSUE TITLE
How can I tell if my bot has connected to OGS?

### ISSUE THREAD

**Issue by flakeman2** [online-go/gtp2ogs#20]
I just setup a bot account today and wanted to test Leela.  I believe I have everything setup correctly but after starting gtp2ogs it just hangs here:

```
dflake@dflake-laptop:~/Desktop/Leela$ /usr/bin/nodejs /usr/local/bin/gtp2ogs --botid flakebot --apikey <key_withheld> -- /home/dflake/Desktop/Leela/leela_090_linux_x64 --gtp --logfile /home/dflake/Desktop/Leela/leela.log
(node) sys is deprecated. Use util instead.
[ggs.online-go.com80] Connecting..https://ggs.online-go.com:80
```

I never see the bot actually connect and it doesn't accept any game challenges.  Any help debugging would be appreciated.  Thanks,

Devin

**Comment by roy7** [comment]
Try adding --debug to gtp2ogs and see if that helps any.

**Comment by anoek** [comment]
@flakeman2 Sorry I hadn't published the new `gtp2ogs` on npm (well outside of the beta tag), so you were using an old client. Try upgrading `gtp2ogs` and trying again?

**Comment by roy7** [comment]
He should also download your devel branch right, not master branch?

**Comment by anoek** [comment]
At this time of the post, that was true, but now master has the version that we're running in production, beta has all the more recent improvements you've been making, so both should be good.

Closing for now as I think this is resolved, feel free to reopen if you're still having issues @flakeman2

**Comment by roy7** [comment]
@flakeman2 As a reference this is the sort of command line I use for Leela:

`node gtp2ogs.js --username RoyalLeela --apikey <key> --debug --kgstime --persist -- Leela090GTP.exe --gtp --noponder --threads 2 --lagbuffer 1000 -p 75000 1>>log 2>&1`

I can't get pondering to work atm but I have some feedback from author to try. I use a high lagbuffer because of recent server performance, but removing use of active_game might solve that substantially. I use a -p cap in case I have some correspondence game and don't want to think 23 hours on them. :) I limit threads since so many RoyalLeela games go on at once now and then.

**Comment by flakeman2** [comment]
Sorry for the late reply - thanks for the tips - that worked perfectly!
