### ISSUE TITLE
Options for max and min rankedhandicap and 'auto' handicaps

### ISSUE THREAD

**Issue by roy7** [online-go/gtp2ogs#28]
Since automatic handicap provides handicap=-1 in the notification, we either need the API add info about our own handicap to the notification (so we can calculate the the expected real handicap at the time of notification) or fetch our user details each time a new challenge arrives.

Currently I just reject auto handicap in my production copy since it is a way away round the maxrankedhandicap setting.

**Comment by roy7** [comment]
Appears automatic handicap is null these days and no longer -1. Similar to automatic komi.

**Comment by wonderingabout** [comment]
no actually you were right @roy7 

i managed to reveal automatic handicap value by replacing `argv.minhandicap` to `notification.handicap` , and this is what i get with `--minhandicap 9` while starting a automatic handicap game

![automatic handicap](https://user-images.githubusercontent.com/38690718/50384818-a4d39180-06ca-11e9-8efa-5b10a2ff42f9.png)

however automatic komi is called "null", so not the same

**Comment by wonderingabout** [comment]
update : 

when trying `--minhandicap -1` i'm getting the following error message : 


![auto handi 2](https://user-images.githubusercontent.com/38690718/50384934-a9994500-06cc-11e9-8951-ed1e2311c93d.png)

**Comment by wonderingabout** [comment]
new problem and its fix !!!

problem : 

as @Dorus noticed, even when setting `--minhandicap` and `--maxhandicap`, if the user is using automatic handicap then the handicap limits get bypassed (and komi then becomes 0.5 in a handicap game btw)

fix : 

for many reasons, add a boolean to enable autohandicap (default is false : disables the automatic handicap)

and this is why : 

undirectly, i found that the autohandicap indeed uses the value `-1`

i found that if i added a new condition "reject games if notification.handicap < argv.autohandicap", then automatic games are rejected, but all manual values for handicap stones (like 1 , 2, 3) that are within the set min-max limits are still allowed

so i created a autohandicap argument
for autohandicap, i set it to default to 0
so `<0` is `-1`  !!!

the -1 value can be used like that

(0 is not stricly inferior to 0 so "none" is allowed)
hence why "none" handicap stones  is still accepted but not automatic handicap (it accepts 0 handicap stones, but reject automatic handicap even when the number of stones ends up being 0)


what is left to do is now to create a boolean for 
`--autohandicap`

i suggest to set it to default false
meaning automatic handicap is rejected, unless the bot admin adds this setting to allow automatic handicap

another advantage of disabling autohandiap by default (possible to use --autohandicap to renable it for bot admin) is to fix some careless issues, for example last time nightlyleela accidentally started a handicap game without wanting it due to handicap set to auto, 

and intuitively "automatic" for the user is a setting that is fine
this accidental use also happened a few times with other users for my bot too

this is what happens when a player now tries to send a game with autohandicap disabled

![autohandicapmsg](https://user-images.githubusercontent.com/38690718/51070733-8c5df380-1646-11e9-823b-41ffb1ce57ee.png)

however, when handicap "none" is selected (0 stones), the game starts no problem :smiley:
this is the limit of what i can do though :smiley:

now it would be great to make it a boolean similar to how `--persist` and `--noclock` work, but i dont have the coding knowledge :smiley: , so i'm counting on you all to make gtp2ogs more awesome and friendly :+1: 


you can test my branch here, it works, but remember that it's not yet a boolean :)
https://github.com/wonderingabout/gtp2ogs/tree/autohandicap-v1-devel

i suggest you use --maxhandicap 0 and test what happens with "none" , "automatic", "0", "1" handicap stones

**Comment by TokumotoK** [comment]
Just a small warning on handicap.
A bot needs to accept auto handicap if it wants to play ranked games.  So this becomes the reject condition priority issue.

If --autohandicap is not set and defaults to false, then the following is needed:
1. If --rankedonly is set, then automatically accept auto handicap
2. If --unrankedonly is not set, then automatically accept auto handicap

This could get confusing to gtp2ogs users if not implemented carefully.

**Comment by wonderingabout** [comment]
@TokumotoK 

indeed, the ideal situation is to allow autohandicap, 

but autohandicap is currently conflicting with max and minhandicap

After discussion on discord, @Dorus told me he can code it so that autohandicap detects the number of handicap stones, so this would fix the issue totally

as for the reject priority, it's already in a pull request if you want to test it, personally i find it much better user experience for the user
here : 
https://github.com/online-go/gtp2ogs/pull/86

i put it in the same branch because i was lazy to clean my existing branch :laughing:

**Comment by TokumotoK** [comment]
Thank you!

**Comment by wonderingabout** [comment]
#104 has been merged into devel now @TokumotoK 

you can upgrade to devel and start using `--noautohandicap` or the ISSA (intuitive semi-syllabic alias) `--nah` if you want :+1: (i'll use it too for all my bots)

note that some features have been renamed like `--maxrankedhandicap` and similar becoming `--maxhandicapranked` for consistency with other ranked arguments like

**Comment by wonderingabout** [comment]
what i added is only a boolean to disable auto handicap, since it bypasses the set min and max handicap limits, as it happened to my bot vs Stefe bot's games

@Dorus was talking about pushing this fix further, by making the "auto handicap" min and max handicap limits as well as take rank into account, 
t.l.d.r : changing the gtp2ogs automatic handicap behaviour, integrated in the code

**Comment by wonderingabout** [comment]
just messaged all bot admins with this : 

```
hi :) if you want to upgrade gtp2ogs to devel you need to make sure you dont use the deprecated old features --botid --id --bot --maxrankedhandicap and co anymore. Now there are many new very nice features on devel !! also, note that --maxrankedhandicap and similar have been renamed to --maxhandicapranked for consistency with other ranked arguments like --nopauseranked --banranked --maxperiodsranked --maxperiodtimeranked --maxmaintimeranked --maxhandicap --noautohandicapranked !!
```

**Comment by wonderingabout** [comment]
almost finished in #121 

need @anoek and @roy7 to set up the challenger object so that we can detect bot ranking and manually apply automatic handicap on it, see PR for details in #121

**Comment by roy7** [comment]
Anoek said he'll try to have new info in the challenge object on Tuesday we can use for this. True handicap isn't set until game is accepted, but since we accept challenges instantly, it should be very rare a rank changes between challenge and acceptance. I can live with that. :)

**Comment by wonderingabout** [comment]
lool

big news @roy7 :+1: 

looking forward to more awesomeness on gtp2ogs

**Comment by wonderingabout** [comment]
just a reminder that after the commotion in the PRs, we forgot to fix the autohandicap bypass of minhandicap maxhandicap limits issue,

in https://github.com/online-go/gtp2ogs/pull/121

maybe we can have a look at this again @roy7 @Dorus @anoek 

big thanks :+1:

**Comment by wonderingabout** [comment]
while server support adds bot ranking detection and/or notification automatic handicap stones, i went ahead and added a `fakerank` code in #183 

still debugging it, but should fix the automatic handicap bypass issue
see #183 for details

**Comment by wonderingabout** [comment]
@roy7 @Dorus @TokumotoK 

the automatic bypass issue is now fixed in #207, see #192 for details as well
this can be closed
bot admin just needs to add a fakerank, for example `--fakerank 8d`

![testi3 fakerank 6d](https://user-images.githubusercontent.com/38690718/70147924-81b8ac80-16a5-11ea-8770-bb09ad6124b7.png)

**Comment by wonderingabout** [comment]
this is the best we can do until server adds support for "automatic" handicap object, which would return us in an handicap object : 
- the type of handicap ("automatic" or "number")
- the number of handicap stones (whether they are automatically calculated or manually by challenge user)

there are 2 main issues currently with handicap automatic : 
1) if minhandicap === 0 (even only), we will reject all automatic (notification.handicap === -1) handicap games (because -1 < 0)
2) currently, there is a bug where in some cases strangely an automatic handicap challenge can bypass the minmax handicap limits set by botadmin
for example minhandicap 2 maxhandicap 5, automatic handicap 2k vs 6d, 8 handicap stones above of max, and this is even in ranked games
see https://github.com/wonderingabout/gtp2ogs/blob/devel/docs/OPTIONS-LIST.md#minhandicap for details
another workaround is to use the `--fakerank` option : https://github.com/wonderingabout/gtp2ogs/blob/devel/docs/OPTIONS-LIST.md#fakeran`

**Comment by wonderingabout** [comment]
since the `-1` handicap exception is not clear, we may add a warning check in console at gtp2ogs start

this was attempted in #255
