### ISSUE TITLE
"Killing bot because of gamedata change after bot was started" loop crash spotted

### ISSUE THREAD

**Issue by wonderingabout** [online-go/gtp2ogs#294]
it seems we finally found a full and simple log to analyze the gamedata change loop crash!! :100: 

# [Download full log (5.5 MB)](https://drive.google.com/file/d/1xZjlsrEIK-1laXjwwj5zwLOEwVQsQWnw/view?usp=sharing)

first line where the bug is spotted is 16325

opening the log file with vs code, we can see that before line 16325 the "killing process directly with a signal" works normally, only once at game end

but starting from line 16325, we have 104 "killing bot because of gamedata change", from time 18:52:29 to time 18:52:44 the bot crash loops repeatedly,
until line 35474 (approximately 1000 lines per second)

@roy7 found on discord the issue and we are working on a fix,

extra screenshots (see yellow bars at the righest for ctrl+f results)

- 104 results for "killing bot because of gamedata change", most crowded at the same place

![gamedata change vs code](https://user-images.githubusercontent.com/38690718/82698656-77966480-9c6b-11ea-9ce1-279b525098b8.png)

- 219 results for "killing process directly with a signal", most abnormally matching the game data changes in blocks such as this one (see screenshot below too)

![vscode rightest](https://user-images.githubusercontent.com/38690718/82698637-6d746600-9c6b-11ea-95cb-cab98f5c5648.png)

Shell
```May 22 18:52:40   bot.js:148                     [52309] Killing process directly with a signal
May 22 18:52:40   bot.js:148                     [52320] Killing process directly with a signal
May 22 18:52:40   bot.js:148                     [52321] Killing process directly with a signal
May 22 18:52:40   bot.js:148                     [52332] Killing process directly with a signal
May 22 18:52:41   bot.js:148                     [52335] Killing process directly with a signal
May 22 18:52:41   bot.js:148                     [52346] Killing process directly with a signal
May 22 18:52:41   bot.js:148                     [52347] Killing process directly with a signal
May 22 18:52:41   bot.js:148                     [52358] Killing process directly with a signal
May 22 18:52:41   bot.js:148                     [52372] Killing process directly with a signal
May 22 18:52:41   bot.js:148                     [52383] Killing process directly with a signal
May 22 18:52:41   bot.js:148                     [52394] Killing process directly with a signal
May 22 18:52:41   bot.js:148                     [52405] Killing process directly with a signal
May 22 18:52:41   bot.js:148                     [52423] Killing process directly with a signal
May 22 18:52:41   bot.js:148                     [52434] Killing process directly with a signal
```

may be similar with #256 and other issues

**Comment by roy7** [comment]
Discord comments:

Okay interesting. One gamedata has clock.now and one doesn't.
That's why they were no longer identical.
Are we writing now into the clock state someplace?
I'm seeing clock.now exists in our "prior" gamedatas, but not in our new gamedata that conflicts in these logs.
Ah, the clock events have a now but the gamedata doesn't.
And I think when we get a clock event we overwrite state.clock with the new clock.
So if we get a gamedata and a clock at the same time, the clock and gamedata.clock conflict because of the missing now field.
I think the re-connect thing is happening twice.
So we get gamedata, then clock, then gamedata a 2nd time.
But the clock doesn't match gamedata.clock
So it has to restart, and this cycle repeats.
Quick solution is to remove state.gamedata.clock.now before comparing current to new. Better solution is to do this but also figure out why 

> Unable to react correctly - re-connect to trigger action based on game state.

 happens twice. We should only need to trigger the re-connect once.
Alternate solution is delete clock.now before we copy it to our state.gamedata. I could only see one place we ever referenced it, and it's old commented out code.
Line 16325 is the first error
A 2nd gamedata came in after clock
After that, the cycle repeated forever. Either because of our double re-connect attempt or some other problem.
Maybe the initial connection took over 1 second if that code is still active and the timeout reconnected us for a 2nd gamedata.
No all seemed to happen in same second so not timeout I guess. Might be good to add mention of timeouts to the log.

**Comment by wonderingabout** [comment]
i can confirm the only difference is the `clock.now`, running a full compare with vs code:

everything else is entirely the same @roy7 

![only difference in gamedata](https://user-images.githubusercontent.com/38690718/82727105-a43c9180-9ce8-11ea-96ae-5cedc89d82b2.png)

**Comment by roy7** [comment]
Yeah so it isn't the clock packet, we don't copy that into state.gamedata.clock like I guessed. We only copy it into state.clock. The problem must be the server is inconsistent.

**Comment by wonderingabout** [comment]
keeping @roy7 's explanations on discord on how the gamedata issue started, for future reference:

(if you comment this too  @roy7 then i can delete this comment)
from:
https://discordapp.com/channels/417022162348802048/677605761165033472/714163203516530809


>The history of how we got here is that originally you'd get one gamedata per game. But eventually you sometimes got a 2nd. If the 2nd has different data you could end up out of sync with servers. So safe choice is just restart bot. But windo added that timeout code because rarely he'd have a game hang for never getting any gamedata at all. Great. But then sometimes he'd get trapped in a restart loop, so we decided to ignore extra gamedata if it hadn't changed, thus breaking the loop and not starting over if we didn't truly need to. But the server is itself sometimes inconsistent in the gamedata contents and sometimes clock would different from gamedata.clock. So we ignore the fields we observe can be inconsistent.

>At this point extra gamedata should be ignored, missing gamedata should time out and be re-requested, and all known instances of inconsistent server behavior are worked around.

>I still feel like the timeout should maybe be over 1 second. I guess it doesn't hurt since we now correctly ignore the excess gamedata packets but we might request a new one we don't truly need if it takes over 1s to originally arrive. I guess even from opposite side of the world though, it should normally be under 1s if things are working normally.
