### ISSUE TITLE
Note on other branch

### ISSUE THREAD

**Issue by roy7** [online-go/gtp2ogs#5]
Hi there, I was just looking for a gtp2ogs option today and found this and then saw you were actively working on it today. While you are in there you might want to check out changes from this branch:

https://github.com/tk44/gtp2ogs

in case anything in there is of use to you. Someone in the OGS forum had mentioned they had to use that branch to get it working in the past.

**Comment by anoek** [comment]
I'm in regular contact with that maintainer, though I don't recall the details about what he had changed. Initially I think it was to add the ability to reject challenges from known abusive users, but since the advent of forced auto-scoring, i don't think that's an issue anymore. On a related note, tk44 successfully connected his bot to the beta system using the devel gtp2ogs so his alterations might be unnecessary now, i'm not sure.

**Comment by roy7** [comment]
He does provide some config options for things like setting time controls. It'd be nice to restrict game offers to specific time limits, board sizes, ranked or unranked, etc.
