### ISSUE TITLE
Minimum main time not supported in Byoyomi

### ISSUE THREAD

**Issue by TokumotoK** [online-go/gtp2ogs#50]
Bifron logged: 
"#  Minimum main time not supported in time control: byoyomi"

I commented out the following 3 lines:
           if ( 
           ["simple","none"].indexOf(notification.time_control.time
           _control) < 0 ) {
with:
           if ((notification.time_control.time_control == "simple")
           || (notification.time_control.time_control == "none")) {
and it seems to work.
Probably the same applies to Maximum main time, too.

**Comment by roy7** [comment]
Someone else mentioned this too, I wonder why it was failing. I use the indexOf() style test in other places too. Any idea why this didn't work? If the type == simple or none, then indexOf should have returned a number above -1.

Or is my test backwards and should be > 0?

**Comment by roy7** [comment]
Ahh ok. What this does

if ( ["simple","none"].indexOf(notification.time_control.time_control) < 0 )

Is say "make an array of simple,none and see if the string is in that array". So if time_control is simple, it'll return 0. If time_control is none it'll return 1. If it is anything else, it'll return -1.

So I had the logic backwards. In the earlier code:

        if (["japanese", "aga", "chinese", "korean"].indexOf(notification.rules) < 0) {
            conn_log("Unhandled rules: " + notification.rules + ", rejecting challenge");
            reject = true;
        }

It "You must be in this list or we fail". I should have listed the time modes other than simple/none in this problem code, or said >-1 instead of <0. Apologies!

**Comment by roy7** [comment]
Fixed via https://github.com/online-go/gtp2ogs/pull/51

**Comment by TokumotoK** [comment]
Thanks a lot.
