### ISSUE TITLE
Add --pausemaxtime

### ISSUE THREAD

**Issue by roy7** [online-go/gtp2ogs#56]
Add an option to allow pausing but with a max time limit. Handle it like --nopause but SetTimeout() instead of resuming immediately. If game resumes, clear the timeout.

**Comment by wonderingabout** [comment]
so as said in #119 i wrote a first draft

ok this is the first draft i wrote for this : 

didnt test it, but it looks quite good

```
        // this can be viewed as a maxperiods + maxperiodtime problem, where period=pause
        // if maxpausetime and 
        if ((config.maxpausetime || config.maxpauses) && clock.pause.paused && !clock.pause.pause_control["stone-removal"] && !clock.pause.pause_control.system && !clock.pause.pause_control.weekend && !clock.pause.pause_control["vacation-" + clock.black_player_id] && !clock.pause.pause_control["vacation-" + clock.white_player_id]) {

            let pausesNumberConsumed = 0; // max is config.maxpauses
            let remainingPausesNumber = config.maxpauses - pausesNumberConsumed; // when = 0, no more pauses allowed
        
            function pausetimeCountdown() {
                if (remainingPausesNumber = 0) {
                    conn_log(`All ${config.maxpauses} have been consumed, no more pauses allowed, resuming the game`);
                    this.sendchat(`All ${config.maxpauses} pauses allowed have been consumed, no more pauses allowed, resuming the game`);
                } else {
                    let i = Date.now(); // current time, will be refreshed every 1 minutes in the loop
                    let pausetimeInitialTime = Date.now(); // date at which we start pausing the game
                    let pausetimeMaxTime = config.maxpausetime + Date.now(); // after the pause starts, the human player has  config.maxpausetime seconds before the game resumes
                    // we send an ingame sendchat to notify the user of pause settings allowed, in human readable time
                    conn_log(`The game has been paused, pausetime allowed : ${timespanToDisplayString(config.maxpausetime)}, remaining pauses allowed : ${timespanToDisplayString(config.maxpauses)}`);
                    this.sendchat(`The game has been paused, pausetime allowed : ${timespanToDisplayString(config.maxpausetime)}, remaining pauses allowed : ${timespanToDisplayString(config.maxpauses)}`);

                    let pausetimeCheck = function()  {
                        if (i >= pausetimeMaxTime) { // when all allowed pause time is consumed
                            pausesNumberConsumed+=1;
                            remainingPausesNumber = config.maxpauses - pausesNumberConsumed;
                            conn_log(`Just consumed one allowed pause, remaining allowed pauses number is : ${remainingPausesNumber}`);
                            this.sendchat(`Just consumed one allowed pause, remaining allowed pauses number is : ${remainingPausesNumber}`);
                        } else {
                            setTimeout(pausetimeCheck, 60000000); //re check every 1 minutes until all pause time is consumed
                        }
                    }
                    pausetimeCheck(); // the code will halt here until one pause period is consumed
                }
            }
        pausetimeCountdown();
      
        }
```

**Comment by wonderingabout** [comment]
as for my thoughts on the need for this issue, here they are :

**Comment by wonderingabout** [comment]
part 1:
@TokumotoK strong or not, i still fail to see why they just cant play a long game like corr or whatever

but if we want to implement that, then we need to also add a --maxpauses (max number of pauses), else the human player can pause the game forever

first, the pause code is here : 
https://github.com/wonderingabout/gtp2ogs/blob/hrr-display-rank--fix-rank-calculation/gtp2ogs.js#L1021-L1027

so : 
- maxpausetime
- maxpauses
- if a game is paused && argv.maxpausetime && !argv.maxpauses) : add ingame chat to notify of pause time allowed and unlimited number of pauses allowed,
- else if a game is paused && argv.maxpausetime && argv.maxpausesadd ingame chat to notify of pause time allowed and max number of pauses allowed,

this may also be an opportunity for us to rethink current pause implementation : 
- add a "pause is not allowed, resuming the game" chat message ingame similar to what was done in #118 

add the new timespanToDisplayString function @Dorus made to display time in human readable (example "5 minutes 30 seconds", not 330 seconds)

**Comment by wonderingabout** [comment]
part 2 : 

i tried to look at this : 

i know how to create a time counter, but i dont know how to define current time (i saw .gettime and date in the code, but i dont know how to use them currently), maybe @roy7 can hint me

edit : i just found this : 

https://github.com/wonderingabout/gtp2ogs/blob/hrr-display-rank--fix-rank-calculation/gtp2ogs.js#L625

i also saw this : 
https://www.w3schools.com/js/js_date_methods.asp

**Comment by wonderingabout** [comment]
part 3 : 

ok i get what you mean now

another thing i'm getting now is that some bots unlike mine support very fast time setting, so it may make sense to play a fast game against these bots

but still 
so basically it's all about "i want to play my moves very fast but i dont want to use the option of setting long time in case something happens and i want to pause for now. I enjoy more the excitement of a limited time game but i still want to be able to pause it"

To me, both these wishes contradict each other : you either want blitz OR you want to be able to stop

because, in this example, its a blitz game : you are supposed to play all the game in one run, and only if you do that can you get the feel of a fast game
pausing in the middle defeats the purpose of it, 
so if something comes and you want to pause, i think the game looses its feel of a blitz game, so better restart a new one to feel the feel of blitz again, as you said your opponent is a bot so you can start as much times as needed (you can even fork to resume where you left)

but if there is a need for such a feature, we can add it no problem,

but i still think for a player's point of view its a better to stick with what you want : 
- fast game -> all in one run
- not sure -> set long time and play fast or slow
- a problem comes and have to go ? no problem, restart a new one or fork from left position

anyways i'm working on the code atm, i hope i can make the --maxpauses and --maxpausetime

**Comment by wonderingabout** [comment]
this makes me realize we should really reverse the argv to --allowpause --allowpauseranked --allowpauseunranked

if a bot admin wants to allow pause he will have the option, but default should be false : pausing games bring much more problems than advantages

looking at gnugo page profile is enough to see most pause games are needlessly paused https://online-go.com/player/58441/GnuGo

human player wants long game ? sure, just set proper corr time and stick with it
or if bot admin doesnt mind it, allow pause +/- maxpauses maxpausetime
i would still never allow pause on ranked games, it defeats the purpose of ranking

**Comment by wonderingabout** [comment]
part 5 : 

> Let's assume you take about 5 minutes for bathroom. Are you saying you should wait 5 minutes for the bot to play each and all the moves for this contingency even if you want a blitz game?

i dont know a single bot that takes 5 minutes per move : royalzero is arround 1 sec/move, even royaleela plays in less than 1 min/per move (and plays faster if you reduce time)

also, you can take a shower before or after a blitz game.. (a blitz game lasts 5 minutes at most)

> Is it fair for the winner of a major tournament to be decided just because he didn't receive an emergency phone call and the opponent did?

yes, this is a competition, it's too bad that one person got an emergency, but he will have to withdraw (or if opponent kindly agrees, they can postpone and play another time, but this is only out of kindness)

> Why would pause defeats the purpose of ranking??

ranking aims at estimating people's strengths and weaknesses in limited time for both players, allow players to pause and it becomes freestyle (one person will use bot, one other person will think for hours for every move, etc...)
and i know that if one person wants to cheat he doesnt need that to do it, but its not a reason to give more opportunities

and more importantly, assuming both humans play fair and competitive, a ranked game should never allow pauses, it just loses its competitive point

finally, i forgot to say but on foxwq or tygem do "strong" players pause games ?
i didnt play there for a long time, but i'm sure they dont
so for a ranked game, really allowing pauses dont make any sense (we can leave the option if bot admin truly wants)

i'm sure that if we allow pauses for unranked only, all of a sudden most players wont pause their games anymore, i wonder why..

**Comment by wonderingabout** [comment]
so finally here is the code i started : 

#120

**Comment by TokumotoK** [comment]
ok, let's discuss here.

> i dont know a single bot that takes 5 minutes per move : royalzero is arround 1 sec/move, even royaleela plays in less than 1 min/per move (and plays faster if you reduce time)
Your not knowing a bot that takes 5 minutes per move does not guarantee there will be none in the future.  Furthermore, if a phone call or whatever takes 1 minute and you are a polite player, are you saying you are not supposed to play blitz games?

> yes, this is a competition, it's too bad that one person got an emergency, but he will have to withdraw (or if opponent kindly agrees, they can postpone and play another time, but this is only out of kindness)
I understand your opinion and some tournament director would take that position, but this can be argued from both sides.  OGS has had pause allowed as default, so in general, your opinion is out of line from what's been accepted as the norm on OGS.
 
> assuming both humans play fair and competitive, a ranked game should never allow pauses
Again, I understand your opinion and see the point, but that is not the position OGS has taken so far.  It is not the place for gtp2ogs to force OGS to change that.  If you strongly believe in that, take the issue to a mod.  I might even support and vote with you if it is well laid out.  But not here, not on gtp2ogs.

> finally, i forgot to say but on foxwq or tygem do "strong" players pause games ?
If they don't, that might strengthen your argument to be taken up with the mods, not here, not on how gtp2ogs should behave.

**Comment by wonderingabout** [comment]
@TokumotoK 

ok too

> Your not knowing a bot that takes 5 minutes per move does not guarantee there will be none in the future.

totally unlikely, except for bot vs bot tournaments with high playouts

> Furthermore, if a phone call or whatever takes 1 minute and you are a polite player, are you saying you are not supposed to play blitz games?

if this happens you either : 
- answer phone call if its an important matter, so resign the game not to make your opponent wait
- or you answer phone later if its not important

> I understand your opinion and some tournament director would take that position, but this can be argued from both sides. OGS has had pause allowed as default, so in general, your opinion is out of line from what's been accepted as the norm on OGS.

in human vs human pause make sense, but for a bot admin its a different matter, the bot is often summoned, and bot admin has little time and no motivation to make the police on ogs and make sure every user is polite (if we add a function hoping user will be good, we are doing it wrong)

also, the historical argument is always a bad one : because something was bad in the past is never a reason not to improve it if possible
we are not forbidding pause for bots, only changing default for most reasonable value for benefits/risk, if truly want, bot admin has still the option to add it back
again, looking at gnugo alone is enough to see there is more drawbacks than advantages to allow pause on bots by default : https://online-go.com/player/58441/GnuGo

> Again, I understand your opinion and see the point, but that is not the position OGS has taken so far. It is not the place for gtp2ogs to force OGS to change that. If you strongly believe in that, take the issue to a mod. I might even support and vote with you if it is well laid out. But not here, not on gtp2ogs.

i dont want to change ogs, i only care about how bots should most efficiently behave when playing against the unefficient humans :+1: 

and to find what is reasonable for that, doing same as human vs human just is a bad approach i think

and again, something bad is not a reason for letting it being bad forever

> If they don't, that might strengthen your argument to be taken up with the mods, not here, not on how gtp2ogs should behave.

same answer : 
bots =/= humans

**Comment by Dorus** [comment]
Can we keep this discussion on topic? Arguing if bot admins should allow or disallow pausing is not relevant here. We should supply the tools, and bot admins can decide how they use them.

Right now my problem with pausing is that it can extend the game beyond reasonable, and i do not want to micromanage my bot every evening by unpausing a ton of paused games.

I run my bot for about 16 hours a day, so when i close it down in the evening, i need to know any ongoing game will at least finish up soon. Also before i had slow hardware and only allowed max 1 game at the same time, so a paused game would block the entire bot.

Both these issues are with long pauses. Long pauses also have the problem that when you restart your bot, you will restart the pause timeout, as right now the bot has no local state, just memory.

Allowing short pauses would be no problem for me, i'm not too worried about people abusing the pause function to extend their own time, so if gtp2ogs suport shot pauses (5-15 minutes), i would totally use that instead of `--nopause`.

Adding a max number of pauses, or a max total pause duration would be a nice bonus to future reduce abuse, but that's not something i'm overly worried about.

**Comment by wonderingabout** [comment]
@Dorus whatever bot admins do is not my concern either

i'm only arguing about the default

considering humans will definitely abuse pause, i think its efficient to revert --nopause to --allowpause (default is to forbid pause, and bot admins have the option to enable it, and while they do that, they may also add a max pausetime and maxpauses number, i think it makes more sense like that too)

**Comment by TokumotoK** [comment]
Dorus is right that we should keep it on topic.

Let me say only this to wonderingabout:

Leela Zero can take 90 seconds for each move now, so I disagree with your view on the future.  Moreover, it has been my dream for a long time to invite bot developers to participate in bot to bot tournaments on OGS. 
Historical argument may be bad IF we are in the position to change those policies, but using something like gtp2ogs to change a policy without the full understanding and support/approval by OGS is wrong, even if it is efficient in your opinion, which I may or I may not agree.

I would like to allow 24 hours pause time.  This will resolve most if not all of the pause problem we see on GnuGo and Fuego, while allowing players to postpone the game for a day for unforeseen events.

**Comment by wonderingabout** [comment]
@TokumotoK 

again, i am not saying we should change ogs behaviour, only reversing the default from false to true

the bot admin still and will always have the option to re-enable pause if truly needed

i know that @roy7 also uses pause like me, which i think makes the most sense (you want long game, just play correspondence at your own speed)

but again, if you use `--allowpause` (or `--allowpauseunranked`) you will still be able to allow pauses same as before, we are not changing anything here, just improving default settings

**Comment by wonderingabout** [comment]
you can view this issue the same as allowing default for auto updates on chrome and firefox

most people dont care about updating their browser, but when it was forced on them, they didnt notice it and whole of a sudden tons less security issues and bugs are to deal with for devs

**Comment by TokumotoK** [comment]
Reversing the default is changing the OGS behavior.  And if it is changed, gtp2ogs will be forcing it on users even if it is not your plan.  I am not even arguing it is good or bad, I really want to get this discussion back on topic.

Gnugo and Fuego pause problem will be solved without reversing the default, and what the default should be is a policy decision.

**Comment by wonderingabout** [comment]
ok, let's get back on topic then

but i dont agree with this though
> Reversing the default is changing the OGS behavior

no, it is only setting a default behaviour for player id 50281, while still giving the possibility to change it to whatever player id 50281 wants

OGS server has nothing to do with that, and has its own code to handle games (i.e humans are still allowed to pause games if the botadmin allows it)

but even to get back on topic, the `--maxpausetime` and `--maxpauses` we are trying to set up make sense only if pause is allowed, so this alone hints that pause should be optional

to be clearer, if `--alllowpause` then we ask ourselves if on top of that, we want to tweak the allowed pause behaviour

that was what made me start all this talk on renaming `--nopause` and co to `--allowpause` and co 

but i have a higher priority thing for now, which is to adress things mentionned in #119 

most importantly autohandicap behaviour which really needs to be fixed

and then i personally want to write some commands so that bots can automatically send games to other players (including other bots) every X time with Y gamesettings, same as what is already available on KGS according to what @nerai told us last time

sorry for my stubborness on this issue, lets work on the code then (as for me, after i take care of these other 2 issues first)

**Comment by roy7** [comment]
I'm all for doing something like a 24 hour default max pause timer. But --nopause won't be the default. I believe default settings for things like pause time, periods, main time, whatever, are more of a 'prevent large impactful errors from an oversight' and not 'we think operators should run their bot this way'. So for instance, our opinion if a bot operator should allow pauses or not isn't the business of gtp2ogs to decide. It should allow pauses by default since OGS allows pauses by default on all games. But we add a 24 hour (or even longer?) default pause limit since "allow pausing until the end of time" isn't intended behavior and we can see how it has corrupted GnuGo/etc over time.

**Comment by wonderingabout** [comment]
i still think my proposal would be more efficient (more benefits, lower risks), but ok let's go with that then

but as @roy7 said in https://github.com/online-go/gtp2ogs/pull/120#issuecomment-461046073 , it seems it will be harder than what i orginally thought (storing time, etc..)

i hope i can look at this again when i settle the first issues, but that wont be soon though

but everyone feel free to use my code and improve it and implement it or whatever way you can use it :+1:

**Comment by wonderingabout** [comment]
sorry everyone, i'm starting to lose some screws here :rofl: , but this is an example of smart allowed thing to do

![smartt](https://user-images.githubusercontent.com/38690718/52354356-8a623700-2a30-11e9-9dbb-ac09d5a737ab.png)

gnugo will lose in 1 minute if needed, but i will never lose (can always pause!)

this so funny looooool (sorry everyone, i'm quite pathetic atm but i'm losing some screws here lol) :rofl:

so better laugh it off a little and forget it, it's quite healthy :+1:
feel free to flag as off-topic :+1:

**Comment by windo** [comment]
Trying to distill the requirements:

  * The default should not be to allow pauses forever (everybody)
  * Pauses must not be forbidden by default (@TokumotoK, @roy7)
  * For live/blitz games, pauses should not be longer than O(10m ... 15m) (@Dorus)
  * Pauses should be as short as possible (@wonderingabout)
  * Default pause should be ~24h (@roy7)

Did I miss something important (sorry, I just skimmmed some of the thread)?

If no, then how about making the `--maxmaintime` of the gametype or the challenge `maintime` for the defaulting to be the `--maxpausetime`? It is not exactly anyone's favorite but kind of close to most of the expectations?

It is still pretty relaxed (probably too relaxed for @wonderingabout?). It does give players a pause that is proportional to what they might optimistically expect in a human game (the other human would not be willing to wait for more than the maintime, for sure) while still bounding the time to what the bot operator was expecting (@Dorus will know when the bots can be turned off).

WDYT?

**Comment by wonderingabout** [comment]
@windo 
as long as pause does not last forever or a very long time (more than 1 week), then i am more than happy with whatever timeout you implement

but note that `--maxmaintime` is depreciated, and now we use instead : 

--maxmaintimeblitz
--maxmaintimeblitzranked
--maxmaintimeblitzunranked
--maxmaintimelive
--maxmaintimeliveranked
--maxmaintimeliveunranked
--maxmaintimecorr
--maxmaintimecorrranked
--maxmaintimecorrunranked

**Comment by Dorus** [comment]
Thanks for sorting everything out, makes it very clear what everybody wants.

I like the idea of max main time as default. Additionally there could be settings, and seperate settings for correspondence vs live vs blitz. 

Another point would be on how to fairly give the bot thinking time during paused games. If somebody pauses a game at 1+1s then the bot would think 1s but the player would have hours. But if unpaused, can this be communicated to the bot in time?

Anyway all these ideas should probably wait till later. Sticking to max main time for now sounds like a great starter pr.

**Comment by roy7** [comment]
I don't think we should try to play games with bot thinking time as a result of pauses. If operator wants smaller pauses or no pauses that is up to them. If a bot allows pondering and long pauses it will think a ton but again that's a user configuration situation. I use pondering but only with a visit cap for instance so it never thinks forever.

**Comment by wonderingabout** [comment]
@roy7 can you rename to --maxpausetime for naming consistency lol

**Comment by wonderingabout** [comment]
@roy7 

can you rename to `--maxpausetime` to be clearer lol :+1:

**Comment by wonderingabout** [comment]
i think `--maxpausetime` is better for naming consistency :+1: 

starting with renaming may be first step into solving this :smile:
