### ISSUE TITLE
Killing bot because of gamedata packet after bot was started

### ISSUE THREAD

**Issue by lemonsqueeze** [online-go/gtp2ogs#60]
Hi again,
I'm getting a bunch of these from time to time:

    gtp2ogs.js:894                 [Game 12124530] Killing bot because of gamedata packet after bot was started

Is this normal ?

**Comment by roy7** [comment]
It happens when the server restarts. It also seems to happen now and then but I don't know why. Maybe one day someone can more cleanly support handling an unexpected gamedata packet, but they aren't supposed to arrive in normal operation once bot is already connected to a game. So as a failsafe if we get one, I just have the bot restart to not risk a corrupt state (bot thinks moves/board is different than server does).

**Comment by TokumotoK** [comment]
My bots get that often as well, and Bifron would be a tad stronger without it.
Not sure how 'cleanly' we could handle an unexpected gamedata, and I feel this is a server issue for @anoek .  I don't see merit for keeping this ticket open on gtp2ogs.
