### ISSUE TITLE
Illegal move

### ISSUE THREAD

**Issue by lemonsqueeze** [online-go/gtp2ogs#69]
Amazingly enough i just witnessed a [game](https://online-go.com/game/12415827) live where gtp2ogs and the engine went completely out of sync as far as board state is concerned, and ended up in illegal move (beginning of the game is fun to watch, makes no sense !). At this point it got stalled and looks like it would have timed out if i hadn't restarted gtp2ogs. This doesn't happen often (looks like i have 6 over 20 day period). I guess i must be attracting bugs at the moment =)

I have both sides' logs so should be able to work out what happened.

@roy7 Have you come across this with Leela as well ? If you keep logs i'd be curious how many 'illegal move' you get. Also that could be a cause for mysterious losses by timeout i guess...

**Comment by lemonsqueeze** [comment]
ogs2gtp log looks like this:
```
#  Accepting challenge, game_id = 12415827
[Game 12415827] gamedata
[Game 12415827] Starting new bot process
[Game 12415827] State loading for new bot
[Game 12415827] genmove b
[Game 12415827] gamedata
[Game 12415827] Killing bot because of gamedata packet after bot was started
[31568] Killing process
[Game 12415827] Starting new bot process
[Game 12415827] State loading for new bot
[Game 12415827] genmove b
[Game 12415827] Playing q16
[Game 12415827] Got     d4
[Game 12415827] genmove b
[Game 12415827] Playing q15
[Game 12415827] Got     q4
[Game 12415827] genmove b
[Game 12415827] Playing p4
[Game 12415827] Got     q3
[Game 12415827] genmove b
[Game 12415827] Playing q5
[Game 12415827] Got     r5
[Game 12415827] genmove b
[Game 12415827] Playing r5
[31590] ? illegal move

**Comment by roy7** [comment]
It might be because of the two game data packets. That means there is some sort of error, or the server is misbehaving, because you should only ever get one game data packet. I try to solve that by killing the bot and we starting it fresh with the newest game data packet, but there must be something wrong there? I have rarely seen the bot try to play illegal moves in the past, and would detect those games by checking if Royal Leela ever timed out on a match. Since the bots should never ever time out. But I haven't seen one myself in a long time.

Maybe you could run with --debug and try to solve it? :)

**Comment by roy7** [comment]
Was it with handicap? Since you received the move from the server but the bot tried to make the same move, somehow that move that came from the server wasn't sent to the bot. I can't think off the top of my head why a valid move coming from the server one issue a plate command to the bot. If your bot keeps a log you could look at that to see the commands it's all from the interface, and if you use the debug option it'll show you all the command sent to the bot as well.

**Comment by roy7** [comment]
I had problems like this long ago, usually involved the player color. You could skim through the commit history and see if I mentioned it specifically. I've personally not witnessed it in a long time though. But for all I know it's still happening. The way I was alerted was like you, some games timed out because I tried to play an illegal move.

**Comment by roy7** [comment]
I can't find exactly what I was thinking of, but just if you want to review some of the historical maybe related issues and solutions: https://github.com/online-go/gtp2ogs/issues/47, https://github.com/online-go/gtp2ogs/issues/24, https://github.com/online-go/gtp2ogs/issues/21. https://github.com/online-go/gtp2ogs/issues/18.

**Comment by lemonsqueeze** [comment]
Ah, my bad, looks like i'm behind all this. Some time ago i changed Bot.kill() to send 'quit' instead of killing the bot but now i see it creates all kinds of nasty side effects: if bot gets killed during genmove now it will still make it through and return a move which is not ignored. genmove may take a few seconds, next bot comes up in the meantime and for this move we end up with 2 bots for the same game...

> I've personally not witnessed it in a long time though. But for all I know it's still happening.

Ok, this makes sense. The race condition is still there, it's just we lose it very very rarely with current code.

**Comment by roy7** [comment]
Yeah I had that exact issue for a while. I was trying to make the bot exit more cleanly to flush its logs, but then I'd have happen exactly what you saw. I tried closing the pipes and tried setting something to detect if a bot was in the middle of being shut down to ignore the genmove, but I don't recall I ever really got it working. So I fell back on just killing the bot immediately.

**Comment by lemonsqueeze** [comment]
I was trying to get pachi to quit on game-over, this way in the logs i can distinguish game-over from stalled game waiting for opponent. Hijacking kill() was not very subtle, what i need is a proper game-over handler. Just realized gamedata is ... state actually, so just need to check when phase changes to 'finished'
Looks like it works this time =)
Could PR it if other people want this.

**Comment by roy7** [comment]
Yeah https://github.com/online-go/gtp2ogs/blob/devel/gtp2ogs.js#L1139 is where that's handled currently.

**Comment by roy7** [comment]
Cool thanks. So safe to close this issue?

**Comment by lemonsqueeze** [comment]
Yup
