### ISSUE TITLE
Komi commands

### ISSUE THREAD

**Issue by roy7** [online-go/gtp2ogs#75]
Eventually need to add an option to require a specific komi, since for instance Leela Zero only understands 7.5 and will only play thinking it's 7.5 no matter what it is really set to. It's be nice to set bot to reject games with other komis. Just no --komi command yet. :)

**Comment by wonderingabout** [comment]
a temporary workaround if your engine only supports one komi value is to manually set komi in gt2ogs.js file
it will trick the bot into thinking the komi of the ogs game is the value you set, while it can be any value
endgame will be wrong, but at least your engine will be able to play

for example for phoenixgo this allows the engine to play games with any komi, even though the scoring will be wrong (but its not a big problem for unranked games, because most games end by resign)

`this.command("komi " + 7.5);`

**Comment by roy7** [comment]
Merged https://github.com/online-go/gtp2ogs/pull/79
